version: "3"
services:
  cyberlens:
    build: .
    ports:
      - 8080:8080
    links:
      - db
      - internal_site
    environment:
      - PGPASSWORD=cyberlens
      - PGDATABASE=cyberlens
      - PGHOST=db:5432
      - PGUSER=postgres
    depends_on:
      - "db"

  client:
    build: client
    ports:
      - 1337:80

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=cyberlens
      - POSTGRES_DB=cyberlens

  internal_site:
    build: internal_site
